name: Article

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: api
          path: ./api/public
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
        working-directory: ./api
      - run: python article.py
        working-directory: ./api
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api/public
          publish_branch: api
